#Diccionario para los mensajes flash
mensajes_flash = {
    
    'es': {
       'archivo_subido_correctamente': 'Archivo subido correctamente',
        'busqueda_eliminada': "Búsqueda eliminada correctamente.",
        'busqueda_no_encontrada': "Búsqueda no encontrada.",
        'busqueda_editada':'Búsqueda editada exitosamente.',
        'campos_incompletos': 'Por favor, completa todos los campos.',
        'contrasena_incorrecta': 'Contraseña incorrecta.',
        'contrasenas_no_coinciden': 'Las contraseñas no coinciden',
        'usuario_existente': 'El nombre de usuario ya está en uso',
        'email_existente': 'El correo electrónico ya está en uso',
        'cuenta_creada': 'Cuenta creada exitosamente',
        'error_guardar': 'Error al guardar el usuario: ',
        'contrasena_longitud': "La contraseña debe tener al menos 8 caracteres.",
        'contrasena_mayuscula': "La contraseña debe incluir al menos una letra mayúscula.",
        'contrasena_minuscula': "La contraseña debe incluir al menos una letra minúscula.",
        'contrasena_numero': "La contraseña debe incluir al menos un número.",
        'contrasenas_no_coinciden': 'Las contraseñas no coinciden.',
        'cuenta_creada': 'Cuenta creada exitosamente.',
        'cerrada_sesion':'Sesión cerrada',
        'correo_no_encontrado':'No existe un usuario con ese correo.',
        'datos_ya_existen': "Ya existen datos para ese año y tipo de estudio.",
        'debes_iniciar_sesion':'Debe iniciar sesión',
        'error_actualizar': "Error al actualizar el perfil: ",
        'error_guardar': 'Error al guardar el usuario: ',
        'errores_formulario': "Hay errores en el formulario. Por favor, corrígelos.",
        'error_contrasena':'Ocurrio un error al actualizar la contraseña.',
        'email_existente': 'El correo electrónico ya está en uso.',
        'formato_anho_invalido': "El año debe tener el formato 2022-2023",
        'mensaje_cargando': "Procesando los datos. Por favor, espere...",
        'no_archivo_encontrado': 'No se encontró el archivo',
        'no_seleccion_archivo': 'No se seleccionó ningún archivo',
        'no_se_puede_modificar_admin':'No se puede modificar el rol del superadmin',
        'no_tienes_permiso':'No tienen permisos suficientes para modificar el rol de otro usuario',
        'perfil_actualizado': "Perfil actualizado correctamente.",
        'tipo_archivo_no_permitido': 'Tipo de archivo no permitido',
        'tipo_estudio_invalido': "Opción de tipo de estudio no válida",
        'usuario_existente': 'El nombre de usuario ya está en uso.',
        'usuario_no_encontrado': 'Correo/Usuario no encontrado.',
        'rol_cambiado':'El rol del usuario ha sido actualizado',
        'rol_ya_tiene':'El usuario ya es administrador',
        'solo_superadmin_degrada':'Solo el superadmin puede degradar a otros administradores',


    },
    
    'en': {
        'archivo_subido_correctamente': 'File uploaded successfully',
        'busqueda_eliminada': "Search successfully deleted.",
        'busqueda_no_encontrada': "Search not found.",
        'busqueda_editada':'Search edited successfully.',
        'campos_incompletos': 'Please complete all fields.',
        'contrasena_incorrecta': 'Incorrect password.',
        'contrasenas_no_coinciden': 'Passwords do not match',
        'usuario_existente': 'Username is already taken',
        'email_existente': 'Email is already in use',
        'cuenta_creada': 'Account successfully created',
        'error_guardar': 'Error saving user: ',
        'contrasena_longitud': "Password must be at least 8 characters long.",
        'contrasena_mayuscula': "Password must include at least one uppercase letter.",
        'contrasena_minuscula': "Password must include at least one lowercase letter.",
        'contrasena_numero': "Password must include at least one number.",
        'contrasenas_no_coinciden': 'Passwords do not match.',
        'cuenta_creada': 'Account successfully created.',
        'correo_no_encontrado':'There is no user with that email.',
        'cerrada_sesion':'Logout sucessfully',
        'datos_ya_existen': "Data already exists for that year and type of study.",
        'debes_iniciar_sesion':'You must login.',
        'error_actualizar': "Error updating profile: ",
        'error_guardar': 'Error saving user: ',
        'errores_formulario': "There are errors in the form. Please correct them.",
        'error_contrasena':'An error occur while updating the password.',
        'email_existente': 'Email is already registered.',
        'formato_anho_invalido': "The year must be in the format 2022-2023",
        'mensaje_cargando': "Processing data. Please wait...",
        'no_archivo_encontrado': 'No file found',
        'no_seleccion_archivo': 'No file selected',
        'no_se_puede_modificar_admin':'Superadmin role cannot be modified',
        'no_tienes_permiso':'You do not have the permissions to modify other users role',
        'perfil_actualizado': "Profile updated successfully.",
        'tipo_archivo_no_permitido': 'File type not allowed',
        'tipo_estudio_invalido': "Invalid study type option",
        'usuario_existente': 'Username is already taken.',
        'usuario_no_encontrado': 'Email/Username not found.',
        'rol_cambiado':'The role of the user has been updated',
        'rol_ya_tiene':'The user has already the role of administrator',
        'solo_superadmin_degrada':'Only the superadmin can degrade to other administrators.',


    }    
}