# Diccionario de traducciones
textos = {
    
    'en': {
        'aceptar': 'Accept',
        'actualizar_perfil': 'Update profile',
        'acciones':'Actions',
        'ajustes': 'Settings',
        'anho':'Select the year range (start date - end date) e.g. 2022-2023',
        'anho_tabla':'Year',
        'api_key': 'API key',
        'archivo_requerido': 'Please, upload an excel file.',
        'base_url': 'URL base',
        'busquedas_anteriores':'Previous Searches',
        'cambiar_fichero':'Change file',
        'cancelar': 'Cancel',
        'cerrar_sesion': 'Logout',
        'cerrar':'close',
        'correo':'Email',
        'correo_usuario':'User email',
        'crear_cuenta': 'Register',
        'confirmar_contrasenha': 'Confirm password',
        'confirmar_eliminacion': 'Confirm deletion',
        'confirmar_eliminacion1': 'Are you sure you want to delete the search with code ',
        'confirmar_eliminacion2': ' from year',
        'contenido': 'Content visible only for visitors.',
        'codigo_Asignatura':'Subject code',
        'criterio_1': 'The password must have at least one uppercase letter, one lowercase letter, and one number.',
        'criterio_2': 'Additionally, a minimum of 8 characters.',
        'criterio_3': '* If you do not fill in the password field, it will not be updated.',
        'datos_IA': 'IA data',
        'descargar_datos_nuevos': 'Download new data',
        'descargar_informe':'Download report',
        'editar':'Edit',
        'ejecutando_grados': 'Downloading the links to the addresses of bachelors and masters degrees.',
        'ejecutando_guias': 'Downloading guias....',
        'ejecutando_asignaturas':'The subjects are being processed..... ',
        'eliminar':'Delete',
        'en': 'English',
        'error_script': 'Error running the script:',
        'espanol': 'Spanish',
        'formato_incorrecto':'Incorrect format. Use the YYYY-YYYY format.',
        'formato_excel_incorrecto':'Incorrect format. Make sure the file has one of the following extensions: .xlsx or .xls',
        'filtrar': 'Filter',
        'guardar':'Save changes',
        'grande':'Big',
        'introducir_rango_anho': 'Enter the range of three years (start year - end year) e.g. 2021-2023',
        'introducir_anho': 'Enter the academic year for which you want to extract the metrics: (start year - end year) e.g. 2023-2024',
        'introducir_datos_IA': 'Enter the following data, if not the default IA will be used (Llama-8B-GGUF)',
        'introducir_codigo': 'Introduce the subject code',
        'IA_tit': 'IA',
        'ingles': 'English',
        'iniciar_sesion': 'Login',
        'informe_1_19':'Annual Operation Maintenance Percentage (1_19)',
        'informe_6_1':'Number of Courses on Environment and Sustainability (6_1)',
        'informe_6_2':'Total number of courses or modules offered (6_2)',
        'informe_6_4':'Total Research Funds Dedicated to Sustainability Research (in US Dollars) (6_4)',
        'informe_6_3':'Ratio of sustainability courses to total courses/subjects (6_3)',
        'informe_6_7':'Number of Scholarly Publications on Sustainability (6_7)',
        'informe_6_8':'Number of Events on Environment and Sustainability(6_8)',
        'ingrese_anho':'Introduce the year',
        'myModel': 'Model',
        'mensaje_cargando': 'Loading... This might take a few minutes...',
        'modo_daltonismo': 'Color blind',
        'modalidad':'Modality',
        'nueva_contrasenha': 'New password. *',
        'nuevo_rol':'New role',
        'no':'No',
        'nombre_archivo':'File name',
        'normal': 'Medium',
        'no_busquedas':'No previous searches were found.',
        'no_resultados':'No results were found for the year ',
        'opcion_ambos':'Both',
        'opcion_grado':'Degree',
        'opcion_master':'Master',
        'opcion_presencial':'Presencial',
        'opcion_online':'Online',
        'pequeno': 'Small',
        'perfil': 'Profile',
        'proceso_completado': 'Process successfully completed for the year',
        'progreso_titulo': 'Process Progress',
        'rango_incorrecto': 'The year range must be exactly 3 years (Example: 2021-2023).',
        'realizar_busqueda_nueva': 'Search',
        'rol_administrador':'Administrator',
        'rol_usuario':'User',
        'rol_cambiar':'Change role',
        'sel_idioma': 'Select language:',
        'sel_letra': 'Select Font Size:',
        'seleccionar_columnas':'Select columns',
        'seleccionar_tipo_estudio' : 'Choose the type: ',
        'seleccionar_informe':'Select the report:',
        'sostenibilidad':'Sustainable',
        'subir_excel': 'Upload your Excel file',
        'si':'Yes',
        'texto_bienvenida': 'Welcome to Greenmetrics',
        'tit_admin': 'Administrator profile',
        'tit_user': 'User profile.',
        'titulo_visit': 'Visitor profile',
        'tipo':'Programme type',
        'todos':'All',
        'usuario': 'User name.',
        'volver_atras': '← Go Back'
        },
    'es': {
        'aceptar': 'Aceptar',
        'actualizar_perfil': 'Actualizar perfil.',
        'acciones':'Acciones',
        'ajustes': 'Ajustes',
        'anho':'Seleccione el rango de años (fecha inicial - fecha final) Ej. 2022-2023',
        'anho_tabla':'Año',
        'api_key': 'API key',
        'archivo_requerido': 'Por favor, añada un fichero excel',
        'base_url': 'Base URL',
        'busquedas_anteriores':'Búsquedas anteriores',
        'cambiar_fichero':'Cambiar el fichero',
        'cancelar': 'Cancelar',
        'cerrar_sesion': 'Cerrar sesión',
        'cerrar':'Cerrar',
        'correo':'Correo',
        'correo_usuario':'Correo del usuario',
        'crear_cuenta': 'Crear cuenta',
        'confirmar_contrasenha': 'Confirmar contraseña',
        'confirmar_eliminacion':'Confirmar eliminación',
        'confirmar_eliminacion1':'¿Estás seguro de que deseas eliminar la búsqueda con código ',
        'confirmar_eliminacion2':' del año',
        'contenido': 'Contenido solo visible para visitantes.',
        'codigo_Asignatura':'Código asignatura',
        'criterio_1': 'La contraseña debe tener al menos una mayúscula, una minúscula y un número.',
        'criterio_2': 'Además de un minimo de 8 caracteres.',
        'criterio_3': '* Si no rellena el campo de la contraseña, esta no se actualizará.',
        'datos_IA': 'Datos de la IA',
        'descargar_datos_nuevos': 'Descargar datos nuevos',
        'descargar_informe':'Descargar informe',
        'editar':'Editar',
        'ejecutando_grados': 'Descargando los enlaces a las direcciones de los grados y masteres.',
        'ejecutando_guias': 'Descargando las guías docentes.....',
        'ejecutando_asignaturas':'Se están procesando las asignaturas.... ',
        'eliminar':'Eliminar',
        'en': 'Inglés',
        'error_script': 'Error al ejecutar el script:',
        'espanol': 'Español',
        'formato_incorrecto':'Formato incorrecto. Use el formato YYYY-YYYY.',
        'formato_excel_incorrecto':'Formato incorrecto. Asegurese del que fichero tiene alguna de lantes extesiones .xlsx o .xls',
        'filtrar': 'Filtrar',
        'guardar':'Guardar cambios',
        'grande':'Grande',
        'introducir_anho': 'Introduzca el curso académico para el que desea extraer las métricas: (año inicio - año final) Ej. 2023-2024 ',
        'introducir_rango_anho': 'Introduzca el rango de tres años  (año inicio - año final) Ej.2021-2023 ',
        'introducir_datos_IA': 'Introduce los siguientes datos, sino se usará la IA predeterminada (Llama-8B-GGUF)',
        'introducir_codigo': 'Introduce el código de asignatura',
        'IA_tit': 'IA',
        'ingles': 'Inglés',
        'iniciar_sesion': 'Iniciar sesión',
        'informe_1_19':'Porcentaje Anual de Operación y Mantenimiento (1_19)',
        'informe_6_1':'Número de cursos sobre Medio Ambiente y Sostenibilidad (6_1)',
        'informe_6_2':'Número total de cursos ofrecidos (6_2)',
        'informe_6_3':'Ratio de cursos sostenibles (6_3)',
        'informe_6_4':'Fondos totales de investigación dedicados a la investigación en sostenibilidad (en dólares estadounidenses) (6_4)',
        'informe_6_7':'Número de publicaciones académicas sobre sostenibilidad (6_7)',
        'informe_6_8':'Número de eventos relacionados con el Medio Ambiente y Sostenibilidad (6_8)',
        'ingrese_anho':'Ingrese el año',
        'myModel': 'Modelo',
        'mensaje_cargando': 'Cargando... Esto puede tardar algunos minutos...',
        'modo_daltonismo': 'Modo Daltonismo',
        'modalidad':'Modalidad',
        'nueva_contrasenha': 'Nueva contraseña. *',
        'nuevo_rol':'Nuevo rol',
        'no':'No',
        'nombre_archivo':'Nombre del archivo:',
        'normal': 'Medio',
        'no_busquedas':'No se encontraron búsquedas anteriores.',
        'no_resultados':'No se encontraron resultados para el año ',
        'opcion_ambos':'Ambos',
        'opcion_grado':'Grado',
        'opcion_master':'Master',
        'opcion_presencial':'Presencial',
        'opcion_online':'Online',
        'pequeno': 'Pequeño',
        'perfil': 'Perfil',
        'proceso_completado': 'Proceso completado exitosamente para el año',
        'progreso_titulo': 'Progreso del Proceso',
        'rango_incorrecto': 'El rango de años debe ser de exactamente 3 años (Ejemplo: 2021-2023).',
        'realizar_busqueda_nueva': 'Realizar una búsqueda',
        'rol_administrador':'Administrador',
        'rol_usuario':'Usuario',
        'rol_cambiar':'Cambiar rol',
        'sel_idioma': 'Seleccionar Idioma:',
        'sel_letra': 'Seleccionar Tamaño de Letra:',
        'seleccionar_columnas':'Seleccionar columnas',
        'seleccionar_tipo_estudio' : 'Selecciona el tipo de estudio',
        'seleccionar_informe':'Selecciona el informe a generar:',
        'sostenibilidad':'Sostenible',
        'subir_excel': 'Suba su fichero excel',
        'si':'Sí',
        'texto_bienvenida': 'Bienvenido a Greenmetrics',
        'tit_admin': 'Perfil de administrador',
        'tit_user': 'Perfil de usuario',
        'titulo_visit': 'Perfil de Visitante',
        'tipo':'Tipo de programa',
        'todos':'Todos',
        'usuario': 'Nombre de usuario',
        'volver_atras': '← Volver atrás'
        }
    }